synology-csi:
  clientInfoSecret:
    create: false
    name: dsm-client-info-secret
  storageClasses:
    delete:
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        protocol: iscsi
        fsType: ext4
        dsm: "nas.kng.rocks"
        location: /volume1/k8s
        formatOptions: --nodiscard
    retain:
      reclaimPolicy: Retain
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        protocol: iscsi
        fsType: ext4
        dsm: "nas.kng.rocks"
        location: /volume1/k8s
        formatOptions: --nodiscard
  volumeSnapshotClasses:
    delete:
      deletionPolicy: Delete
      parameters:
        description: Synology CSI
    retain:
      deletionPolicy: Retain
      parameters:
        description: Synology CSI