---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home
  namespace: {{ .Release.Namespace }}
spec:
  avoidBuggyIPs: true
  addresses:
    # Reserved for MetalLB
    - 10.0.1.128-10.0.1.132
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - home