apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- metallb.yaml
- op-connect.yaml
- cert-manager.yaml
- ingress-nginx.yaml
- external-dns.yaml
- argocd.yaml
- synology-csi