apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
     argocd.argoproj.io/sync-wave: "-9"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: cluster/apps/core/metallb
    repoURL: git@github.com:tsotsos/k8s-home.git
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
