---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: op-connect
  namespace: argocd
  annotations:
     argocd.argoproj.io/sync-wave: "-7"
spec:
  destination:
    namespace: op-connect
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tsotsos/k8s-home
    targetRevision: main
    path: cluster/apps/core/op-connect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true