apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  annotations:
     argocd.argoproj.io/sync-wave: "-9"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: argo-apps/
    repoURL: https://github.com/tsotsos/k8s-home
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
