cert-manager:
  installCRDs: true
  cainjector:
    enabled: true
  extraArgs: 
     - --dns01-recursive-nameservers-only
     - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  deploymentAnnotations:
    operator.1password.io/item-path: vaults/homelab/items/cloudflare-api-token
    operator.1password.io/item-name: cloudflare-api-token